### ISSUE TITLE
Bug located in ...

### ISSUE THREAD

**Issue by AlfGNC** [pyansys/pyfluent#950] opened 2022-09-29 09:23 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![image](https://user-images.githubusercontent.com/74142883/192993641-6126b154-0c26-478b-977d-fbd45c4a0bad.png)
Trying to create a plane, it seems that everything work properly but the definition of point vector.

### 📝 Steps to reproduce

1. Launch Case Session
2. Load .cas and .dat
3. Execute root command

### 💻 Which operating system are you using?

Linux

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
absl-py==0.10.0
backcall==0.2.0
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
colorama==0.4.3
cycler==0.10.0
Cython==0.29.13
decorator==5.1.1
entrypoints==0.4
feather-format==0.4.1
future==0.18.2
google-auth==1.21.1
google-auth-oauthlib==0.4.1
grpcio==1.32.0
h5py==2.10.0
idna==2.10
importlib-metadata==1.7.0
ipykernel==5.5.6
ipython==7.16.3
ipython-genutils==0.2.0
jedi==0.17.2
joblib==0.16.0
jupyter-client==7.1.2
jupyter-core==4.9.2
Keras==2.4.3
keras-tuner==1.0.1
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib==3.3.1
msgpack-python==0.5.6
nest-asyncio==1.5.5
numpy==1.19.2
oauthlib==3.1.0
opencv-python==4.4.0.42
pandas==1.1.2
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
prompt-toolkit==3.0.30
protobuf==3.13.0
ptyprocess==0.7.0
pyarrow==1.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydot==1.4.1
pyfluent==0.2.1
Pygments==2.13.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
pyzmq==23.2.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-learn==0.23.2
scipy==1.5.2
six==1.15.0
tabulate==0.8.7
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
terminaltables==3.1.0
threadpoolctl==2.1.0
torch==1.6.0+cu92
torchvision==0.7.0+cu92
tornado==6.1
tqdm==4.48.2
traitlets==4.3.3
urllib3==1.25.10
wcwidth==0.2.5
Werkzeug==1.0.1
zipp==3.1.0
```

**Comment by seanpearsonuk** [comment] 2022-10-17 11:06
point_vector seems to behave like  read-only parameter. Tried setting it to values via API that can be set by other means in the UI but via API it always stays at the old value.

**Comment by seanpearsonuk** [comment] 2022-10-17 11:12
bug 726205 in Fluent

**Comment by seanpearsonuk** [comment] 2023-04-14 10:20
Fixed in Fluent 2023R2, not yet released.

**Closed** 2023-04-14 10:20 UTC
Labels: bug, Fluent, Settings API

**Comment by seanpearsonuk** [comment] 2023-04-14 10:21
@prmukherj if you have a bit of spare time, please could you check this defect?

**Comment by seanpearsonuk** [comment] 2023-04-14 10:52
@cj-hodgson perhaps one for JM to check?

**Comment by cj-hodgson** [comment] 2023-07-27 13:04
@millerj97 Please could you check this.

**Comment by millerj97** [comment] 2023-08-08 08:36
@cj-hodgson tested in pyfluent and pyconsole, confirmed fixed
Steps:
- launch pyfluent and load case/data
- create plane using below commands
````
tester = solver.results.surfaces.plane_surface.create(name = 'test_plane')
tester.method = 'point-and-normal'
tester.print_state()
````
- Defaults to;
    point_vector 0.0, 0.0, 0.0
    point_normal 1, 0, 0

- Modify point values
````
tester.point_vector = (2.12, -0.377, 0.23)
tester.point_normal = (0, 1.34, 0)
tester.print_state()
````
- Modify point_vector and point_normal to multiple values and print state
````
tester.point_vector = (2.8, 0.1, 0)
````
- Load case/data in pyconsole and create plane in point-normal mode with UI
- Edit the created plane using pyconsole commands
````
tester.point_vector = [2.8, 0.1, 0]
````
- Point_vector settings confirmed to update as required
-  Repeat above steps creating point-normal plane and editing, using console commands
