### ISSUE TITLE
command attributes issue

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#895] opened 2022-09-16 10:03 UTC
Command attributes not working properly in (some/all ?) cases. As reported by @ajain-work

```
command_object
<ansys.fluent.core.solver.flobject.setup_unsteady_statistics object at 0x000002910AD05730>
attrs=command_object.get_attrs(["active?"])
attrs is None
True
```

@ajain-work please add any details you think are needed here

**Comment by prmukherj** [comment] 2022-09-20 09:58
from ansys.fluent.core.session import Session
session = Session("10.18.xx.xx", 0000, cleanup_on_exit=False)
root=session.solver.root
solution = getattr(root,"solution")
runCalculation = getattr(solution,"run_calculation")
cmd_object= getattr(runCalculation, "dual_time_iterate", None)
attrs=cmd_object.get_attrs(["active?"])
attrs is None
cmd_object.is_active()

**Comment by seanpearsonuk** [comment] 2022-09-20 10:03
Require server side fix for the command argument attributes

**Comment by mkundu1** [comment] 2022-09-21 13:07
Looking at the proto file response structure for GetAttrs (for PyFluent) and scheme implementation of api-get-attrs (for PyConsole), the difference in the return value structure of get_attrs is expected by design. So, we can go ahead with the defensive check which @prmukherj has already committed in a PR.

**Closed** 2022-09-22 14:32 UTC
Labels: bug
