### ISSUE TITLE
Error with accessing attributes for file_type in settings api

### ISSUE THREAD

**Issue by snallamoansys** [pyansys/pyfluent#466] opened 2022-06-07 10:29 UTC
![image](https://user-images.githubusercontent.com/99287292/172358537-8a7e8309-2cda-4b77-8279-c29ce247af9f.png)

**Comment by seanpearsonuk** [comment] 2022-08-09 11:50
closing as duplicate of (later issue) https://github.com/pyansys/pyfluent/issues/466

**Closed by seanpearsonuk** 2022-08-09 11:50 UTC
Labels: bug
