### ISSUE TITLE
Generation of point-and-direction surface

### ISSUE THREAD

**Issue by PyPablo** [pyansys/pyfluent#1305] opened 2023-01-24 18:12 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When creating a surface. the following

`surface = session.results.surfaces
surface.plane_surface['plane-0'] ={
    'methods': 'point-and-normal',
    'point_vector': [-0.2, -0.15,  0.0],
    'point_normal': [1.0, 0.0, 0.0],
    'compute_from_view_plane': True,
    'surface_aligned_normal': ''}
`
Creates a surface with the right normal but completely incorrect point.

Tested both 
Fluent 23.1 and 23.2
PyFluent '0.12.dev13'

### 📝 Steps to reproduce

Execute above command in any case

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
NA
```

**Comment by mkundu1** [comment] 2023-03-01 16:41
The issue is reproducible in PyConsole also

**Comment by mkundu1** [comment] 2023-03-01 17:02
I have a Fluent side PR to fix this.

**Comment by seanpearsonuk** [comment] 2023-03-01 18:13
There might also be a duplicate. I remember this kind of issue being there a long time ago.

**Comment by mkundu1** [comment] 2023-03-02 11:33
Fix merged in Fluent

**Closed by mkundu1** 2023-03-02 11:33 UTC
Labels: bug, Fluent
